<a href="https://colab.research.google.com/github/RaymondLeong94/DS-Phase-3-Project/blob/main/Notebook_3%2B4_Model_and_results_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#https://www.youtube.com/watch?v=Fuw0wv3X-0o

In [2]:
import pandas as pd
import json
from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [3]:
%cd gdrive/MyDrive

/content/gdrive/MyDrive


In [22]:
import json
preprocessed3 = pd.read_json('/content/gdrive/MyDrive/final_preprocessed_data.json', encoding='utf8') 

In [23]:
practice_set= preprocessed3
practice_set.head()

business_id  stars_x  review_count ByAppointmentOnly  \
0  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
1  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
2  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
3  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
4  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   

  BusinessAcceptsCreditCards CoatCheck RestaurantsTakeOut RestaurantsDelivery  \
0                      False   unknown               True               False   
1                      False   unknown               True               False   
2                      False   unknown               True               False   
3                      False   unknown               True               False   
4                      False   unknown               True               False   

  Caters     WiFi  ... stars_y  \
0   True  u'free'  ...       4   
1   True  u'free'  ...       4   
2   True  u'free'  ...       5   
3   True  u'free'  ...       5   
4   True  u'free'  ...       4   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 This is nice little Chinese bakery in the heart of Philadelphia's Chinatown! The female cashier was very friendly (flirtatious!) and the pastries shown in nicely adorned display cases. I stopped by early one evening had a sesame ball, which was filled with bean paste. The glutinous rice of the ball was nicely flavored, similar to Bai Tang Gao. Definitely as place worth stopping at if you are in the area.   
1                                                                                                                                                                                                                                                                                                                                                                                       This is the bakery I usually go to in Chinatown.  They have a decent variety of buns and pastries.  Red bean-filled buns, mung bean-filled buns, coconut stuff, egg tarts etc.  If you buy a dozen, they will give you two more for free.  The prices are standard for a Chinese bakery, with most things at approximately $1.  The service has always been good.  They do serve coffee and tea.  There are a couple of tables inside, with usually the expected group of older Chinese guys chillin' in the corner table debating about something.  Great place to

In [24]:
practice_set= practice_set[['nouns_adjec', 'stars_y']]

In [7]:

practice_set = practice_set.reset_index()

In [25]:
practice_set

nouns_adjec  \
0                                                                                                                                                                                                                                              'heart', 'philadelphia', 'female', 'cashier', 'pastry', 'show', 'display', 'case', 'evening', 'sesame', 'ball', 'paste', 'rice', 'ball', 'bai', 'tang', 'gao', 'area''nice', 'little', 'bakery', 'chinatown', 'flirtatious', 'adorn', 'fill', 'bean', 'glutinous', 'similar', 'place', 'worth'   
1                                                                                                                                                                       'bakery', 'variety', 'bun', 'pastry', 'bun', 'mung', 'coconut', 'stuff', 'egg', 'tart', 'dozen', 'price', 'standard', 'thing', 'service', 'serve', 'coffee', 'tea', 'couple', 'group', 'guy', 'chillin', 'corner', 'debate', 'something', 'place', 'stock', 'bun', 'town''chinatown', 'decent', 'beanfilled', 'bun', 'free', 'good', 'table', 'old', 'table', 'great'   
2                                                                                                                                                                                                                                                                                                                                                                                  'kind', 'service', 'everyone', 'treat', 'treat', 'judgement', 'theyre', 'favorite''delightful', 'chinatown', 'clean', 'happy', 'delicious', 'ton', 'sweet'   
3                                                                                                                                                                                                                                                                                                                                                                                                                                                 'order', 'graduation', 'event', 'staff', 'nice''niece', 'perfect', 'come', 'future', 'good'   
4      'milk', 'saint', 'honore', 'pastry', 'business', 'boyfriend', 'time', 'cross', 'mind', 'try', 'think', 'year', 'try', 'hkstyle', 'milk', 'tea', 'hook', 'think', 'day', 'week', 'milk', 'tea', 'sugar', 'i', 'zhong', 'gang', 'milk', 'day', 'ice', 'ice', 'etc', 'note', 'try', 'crispy', 'roast', 'pork', 'bun', 'name', 'pork', 'bun', 'crispy', 'roast', 'pork', 'bun''hkstyle', 'sure', 'memorable', 'decide', 'watch', 'good', 'good', 'hkstyle', 'certain', 'lady', 'enough', 'much', 'side', 'wrong', 'roast', 'decent', 'try'   
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ...   
67359                                                                                                                                                                                                                                                                                                                                                                                 'coffee', 'shop', 'work', 'price', 'variety', 'beverage', 'cold', 'choose', 'selection', 'something', 'eat''cute', 'low', 'nice', 'hot', 'seem', 'nice'   
67360                                                                                                                                                                                                                                                                                     

In [26]:
#idea from https://www.youtube.com/watch?v=Fuw0wv3X-0o
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [27]:
#convert
practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)

<ipython-input-27-5f837cc53c80>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)


In [28]:
pd.set_option("max_colwidth", None)

In [29]:
practice_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65698 entries, 0 to 67363
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   nouns_adjec  65698 non-null  object
 1   stars_y      65698 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 1.5+ MB


In [30]:
practice_set['nouns_adjec']

0                                                                                                                                                                                                                                                'heart', 'philadelphia', 'female', 'cashier', 'pastry', 'show', 'display', 'case', 'evening', 'sesame', 'ball', 'paste', 'rice', 'ball', 'bai', 'tang', 'gao', 'area''nice', 'little', 'bakery', 'chinatown', 'flirtatious', 'adorn', 'fill', 'bean', 'glutinous', 'similar', 'place', 'worth'
1                                                                                                                                                                         'bakery', 'variety', 'bun', 'pastry', 'bun', 'mung', 'coconut', 'stuff', 'egg', 'tart', 'dozen', 'price', 'standard', 'thing', 'service', 'serve', 'coffee', 'tea', 'couple', 'group', 'guy', 'chillin', 'corner', 'debate', 'something', 'place', 'stock', 'bun', 'town''chinatown', 'decent', 'beanfilled', 

In [31]:
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].astype(str).apply(lambda x: x.replace('"', ''))

<ipython-input-31-4933b39ab411>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['nouns_adjec'] = practice_set['nouns_adjec'].astype(str).apply(lambda x: x.replace('"', ''))


In [32]:
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace('[', ''))
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace(']', ''))
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace(',', ''))
practice_set['nouns_adjec'] =practice_set['nouns_adjec'].apply(lambda x: x.replace(", '", "'"))
practice_set['nouns_adjec'] =practice_set['nouns_adjec'].apply(lambda x: x.replace("'", ""))

<ipython-input-32-63d9651a53b3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace('[', ''))
<ipython-input-32-63d9651a53b3>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace(']', ''))
<ipython-input-32-63d9651a53b3>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_inde

In [33]:
practice_set

nouns_adjec  \
0                                                                                                                                                 heart philadelphia female cashier pastry show display case evening sesame ball paste rice ball bai tang gao areanice little bakery chinatown flirtatious adorn fill bean glutinous similar place worth   
1                                                                                                     bakery variety bun pastry bun mung coconut stuff egg tart dozen price standard thing service serve coffee tea couple group guy chillin corner debate something place stock bun townchinatown decent beanfilled bun free good table old table great   
2                                                                                                                                                                                                                                        kind service everyone treat treat judgement theyre favoritedelightful chinatown clean happy delicious ton sweet   
3                                                                                                                                                                                                                                                                                        order graduation event staff niceniece perfect come future good   
4      milk saint honore pastry business boyfriend time cross mind try think year try hkstyle milk tea hook think day week milk tea sugar i zhong gang milk day ice ice etc note try crispy roast pork bun name pork bun crispy roast pork bunhkstyle sure memorable decide watch good good hkstyle certain lady enough much side wrong roast decent try   
...                                                                                                                                                                                                                                                                                                                                                  ...   
67359                                                                                                                                                                                                                                             coffee shop work price variety beverage cold choose selection something eatcute low nice hot seem nice   
67360                                                                                                                                                                                                                                                           cash coffee spot cozy spot coffee medium latte get time partnice invite pick ordered bad   
67361                                                                                                                                                                                                                                                hand ice coffee terrific guy counter try apartment bella vista place vote apartment goodfreak close   
67362                                                                         place chill corner coffee shop baristaowner neighborhood order tea afternoon jerk get anyway say day judgment pushiness pastry nothing complain chairgreat super nonpretentious friendly iced free wifi im know im cheap comfortable awesome great little comfortable much   
67363                                                                                                                                                                                                                                                                   neighborhood gem owner guy place spot hang work coffeesuper nice great delicious   

       stars_y  
0            4  
1            4  
2            5  
3            5  
4            4  
...        ...  
67359        5  
67360        3  
673

In [34]:
import nltk
from gensim.models import Word2Vec, KeyedVectors


In [35]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [36]:
practice_set['nouns_adjec']

0                                                                                                                                                   heart philadelphia female cashier pastry show display case evening sesame ball paste rice ball bai tang gao areanice little bakery chinatown flirtatious adorn fill bean glutinous similar place worth
1                                                                                                       bakery variety bun pastry bun mung coconut stuff egg tart dozen price standard thing service serve coffee tea couple group guy chillin corner debate something place stock bun townchinatown decent beanfilled bun free good table old table great
2                                                                                                                                                                                                                                          kind service everyone treat treat judgement theyre favoritedelightful c

In [37]:
from nltk import word_tokenize
nltk.download('punkt') 

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [38]:
practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)

<ipython-input-38-7285264f639a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)


In [39]:
corpus =  practice_set['nouns_adjec'].map(word_tokenize)


In [41]:
corpus

0                                                                                                                                                                                  [heart, philadelphia, female, cashier, pastry, show, display, case, evening, sesame, ball, paste, rice, ball, bai, tang, gao, areanice, little, bakery, chinatown, flirtatious, adorn, fill, bean, glutinous, similar, place, worth]
1                                                                                                                             [bakery, variety, bun, pastry, bun, mung, coconut, stuff, egg, tart, dozen, price, standard, thing, service, serve, coffee, tea, couple, group, guy, chillin, corner, debate, something, place, stock, bun, townchinatown, decent, beanfilled, bun, free, good, table, old, table, great]
2                                                                                                                                                                                       

In [42]:
#min count = 1 for freq 
#vectorsize = 100 
#windows = amount it will go left and right 
model = Word2Vec(corpus, size=300, min_count = 1, window = 10)

In [43]:
vocabulary = model.wv.vocab

In [44]:
vocabulary


{'heart': <gensim.models.keyedvectors.Vocab at 0x7f6b596d15e0>,
 'philadelphia': <gensim.models.keyedvectors.Vocab at 0x7f6b596d16a0>,
 'female': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1700>,
 'cashier': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1610>,
 'pastry': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1550>,
 'show': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1640>,
 'display': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1820>,
 'case': <gensim.models.keyedvectors.Vocab at 0x7f6b596d10d0>,
 'evening': <gensim.models.keyedvectors.Vocab at 0x7f6b596d18b0>,
 'sesame': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1910>,
 'ball': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1970>,
 'paste': <gensim.models.keyedvectors.Vocab at 0x7f6b596d19d0>,
 'rice': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1a00>,
 'bai': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1a90>,
 'tang': <gensim.models.keyedvectors.Vocab at 0x7f6b596d1af0>,
 'gao': <gensim.models.keyedvec

In [45]:
model1 = model.wv

In [49]:
model1.most_similar('manager')

[('response', 0.9297802448272705),
 ('respond', 0.9219815731048584),
 ('apology', 0.9215949773788452),
 ('situation', 0.9046130180358887),
 ('manner', 0.9019166231155396),
 ('explanation', 0.8824670910835266),
 ('contact', 0.8813174962997437),
 ('inconvenience', 0.8811042308807373),
 ('inform', 0.8794299364089966),
 ('delay', 0.878964364528656)]

In [50]:
model1.most_similar("flavor")

[('texture', 0.8917512893676758),
 ('balance', 0.8716511726379395),
 ('combination', 0.8402526378631592),
 ('consistency', 0.8312594890594482),
 ('deathrowmeal', 0.811394989490509),
 ('hint', 0.8042358756065369),
 ('spice', 0.8004513382911682),
 ('preference', 0.7998554706573486),
 ('profile', 0.7940469980239868),
 ('reggiano', 0.7902443408966064)]

In [51]:
for_keras= practice_set['nouns_adjec'].values

In [52]:
for_keras

array(['heart philadelphia female cashier pastry show display case evening sesame ball paste rice ball bai tang gao areanice little bakery chinatown flirtatious adorn fill bean glutinous similar place worth',
       'bakery variety bun pastry bun mung coconut stuff egg tart dozen price standard thing service serve coffee tea couple group guy chillin corner debate something place stock bun townchinatown decent beanfilled bun free good table old table great',
       'kind service everyone treat treat judgement theyre favoritedelightful chinatown clean happy delicious ton sweet',
       ...,
       'hand ice coffee terrific guy counter try apartment bella vista place vote apartment goodfreak close',
       'place chill corner coffee shop baristaowner neighborhood order tea afternoon jerk get anyway say day judgment pushiness pastry nothing complain chairgreat super nonpretentious friendly iced free wifi im know im cheap comfortable awesome great little comfortable much',
       'neighborh

In [53]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [54]:
vocab_size = 300
encoded_reviews = [one_hot(x, vocab_size) for x in for_keras]
print(encoded_reviews)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [55]:
max_length = 10
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[113 193 178 ... 227 175 170]
 [ 16 110 169 ...  44  34  34]
 [171 102 228 ... 177 171 162]
 ...
 [252 283  46 ...  46  63  64]
 [ 83 286  83 ... 142 222 101]
 [136 283 175 ...  72  34 177]]


In [56]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [57]:
practice_set.columns

Index(['nouns_adjec', 'stars_y'], dtype='object')

In [58]:
def stars_transform(x):
  if x >= 3.5:
    return 1
  else:
    return 0 


practice_set['stars_y'] = practice_set['stars_y'].apply(stars_transform)

<ipython-input-58-3b0cd9d07dc3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice_set['stars_y'] = practice_set['stars_y'].apply(stars_transform)


In [59]:
practice_set['stars_y'].value_counts()

1    45608
0    20090
Name: stars_y, dtype: int64

In [60]:
sentiment = practice_set['stars_y'].values.flatten()

In [61]:
X = padded_reviews
y=sentiment

In [62]:
sentiment


array([1, 1, 1, ..., 1, 1, 1])

In [63]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 5)             1500      
                                                                 
 flatten (Flatten)           (None, 50)                0         
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 1,551
Trainable params: 1,551
Non-trainable params: 0
_________________________________________________________________


In [64]:
model.fit(X, y, epochs=50, verbose=0)

In [65]:
loss, accuracy = model.evaluate(X,y)
accuracy

2054/2054 [==============================] - 3s 2ms/step - loss: 0.4912 - accuracy: 0.7633


0.7633413672447205

In [ ]:
model.get_layer('embedding').get_weights()[0]

array([[-0.08514103, -0.23153287,  0.24459454, -0.3646788 , -0.25075015],
       [-0.2938213 ,  0.07905864,  0.3493986 , -1.0039985 , -0.11557846],
       [-0.34502858, -0.07566555, -0.0161044 , -0.06921784, -0.3675889 ],
       ...,
       [-0.39592603, -0.27611938,  0.35098198,  0.09522876,  0.12187388],
       [-0.31211022, -0.16910024,  0.5180508 , -0.35287592, -0.57010895],
       [-0.465337  , -0.43238527,  0.5847294 , -0.07537656, -0.48818544]],
      dtype=float32)